version: '3.9'

services:
  websocket-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app
    tty: true
    # command: "node server.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    # command: "npm run dev"
    tty: true
    environment:
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8080

volumes:
  node_modules:
